# Copy-paste from https://github.com/starkandwayne/concourse-tutorial/blob/master/tutorials/basic/basic-pipeline/pipeline.yml

---
jobs:
  - name: job-hello-world
    public: true
    plan:
      - task: hello-world
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: busybox}
          run:
            path: echo
            args: [This simple pipeline will echo this sentence back to us on the command line]

